# Generated by Django 2.2.5 on 2019-09-21 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('max_carry_weight', models.IntegerField()),
                ('reg_no', models.CharField(max_length=20)),
            ],
        ),
    ]
