# Generated by Django 2.2.5 on 2019-09-21 14:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WasteType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('P', 'Placed'), ('U', 'Picked Up'), ('T', 'In Transist'), ('R', 'Recieved at collection center')], max_length=1)),
                ('weight', models.IntegerField()),
                ('date_of_order', models.DateField(auto_now_add=True)),
                ('assigned_driver', models.ForeignKey(limit_choices_to={'user_type': 'D'}, on_delete=django.db.models.deletion.PROTECT, related_name='Driver', to=settings.AUTH_USER_MODEL)),
                ('user_details', models.ForeignKey(limit_choices_to={'user_type': 'U'}, on_delete=django.db.models.deletion.PROTECT, related_name='User', to=settings.AUTH_USER_MODEL)),
                ('waste_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order.WasteType')),
            ],
        ),
    ]
