# Generated by Django 2.2.5 on 2019-09-21 17:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pickup_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 21, 17, 59, 0, 426612)),
            preserve_default=False,
        ),
    ]
